apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-store
    kind: ClusterSecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: database-user
      remoteRef:
        key: postgres-user
    - secretKey: database-password
      remoteRef:
        key: postgres-password
    - secretKey: database-name
      remoteRef:
        key: postgres-db
    - secretKey: backend-api-key
      remoteRef:
        key: backend-api-key
